### ISSUE TITLE
下载问题求助

### ISSUE THREAD

**Issue by pnufm5qz** [301Moved/ScienceDecrypting#11]
(_Deleted_)

**Comment by rffaxs** [comment]
第二本，https://transfer.sh/1YETRQW/BAA11010DD3B124DCE053010B0A0AD5F5000.pdf

**Comment by pnufm5qz** [comment]
> 
> 
> 第二本，https://transfer.sh/1YETRQW/BAA11010DD3B124DCE053010B0A0AD5F5000.pdf

非常感谢！能请您把第一本的文件也发给我吗？

**Comment by rffaxs** [comment]
第一本，用软件解码暂时报错，待恢复后吧。

**Comment by pnufm5qz** [comment]
> 
> 
> 第一本，用软件解码暂时报错，待恢复后吧。

好，感谢！

**Comment by pnufm5qz** [comment]
问题已经通过别的方式解决，感谢二位大佬！请@301Moved 直接删除此issue
