### ISSUE TITLE
较新年份文件格式不能正确解析

### ISSUE THREAD

**Issue by pigolaj121** [301Moved/ScienceDecrypting#15]
很好用，试了很多本都可以完美解密，但 [这本书](https://transfer.sh/jHbx1P/%E6%95%B0%E5%AD%A6%E5%88%86%E6%9E%90%E8%AE%B2%E4%B9%89%EF%BC%88%E7%AC%AC%E4%B8%89%E5%86%8C%EF%BC%89.pdf) 在一开始的解析阶段报错：

[Log] 解析源文件....
[Error] 解密失败，未知错误:  not well-formed (invalid token): line 2, column 0

还有好几本也遇到这种情况，[有些](https://transfer.sh/VBNpDz/%E6%95%B0%E5%AD%A6%E5%88%86%E6%9E%90%E7%A0%94%E5%AD%A6%209-21.pdf)  是 syntax error: line 1, column 0，都是在解析文件时报错，我发现这些都是较新年份的书，会不会是他们内部格式有了新变化

**Comment by rffaxs** [comment]
这本用Cajviewer都打不开，应该是下载没有完成（网速或者代理等影响）。
这边重新通过SR网站下载，测试一切正常。

**Comment by rffaxs** [comment]
对于一些超过1GB的，如B84E2D8813F194ABFE053010B0A0A6389000，估计是CAJViewerDRM服务器处理能力问题，这种我是无论怎么下载都打不开。

**Comment by pigolaj121** [comment]
你是作者吗，我用hex编辑器看了，和能解密的文件对比了，大体格式一致， 排除了下载不完整的问题。
数学分析这3册，一样下载，1 2 册都没问题，就 3 册有问题，我重下了也不行
我是用学校代理下载的
我现在正在自己看源码，虽然水平有限，希望能找出原因

**Comment by pigolaj121** [comment]
你能把你下载的能解密的数学分析3原始加密文件发一下吗，我看看和我下的有何不同

**Comment by pigolaj121** [comment]
我解决了，文件最后 startright 两个数字是解谜信息开始结束标志，不知为何我下载的这个文件这个信息是错误的，我用 hex 编辑器重新修正了文件，再运行脚本就成功解密了

**Comment by pigolaj121** [comment]
@rffaxs 我发现我解决的 数学分析3 第95页显示有问题（实体书页码，只有这一页，其他页都正常显示），我觉得是它网站原始文件就有问题，你能帮我看看你那边确认一下吗

**Comment by rffaxs** [comment]
我这边测试是正常的，[95页]([url](https://transfer.sh/Ns8g4G/95.pdf))

**Comment by 301Moved** [comment]
这两本都是一样的问题，下载下来的文件有一小段内容有问题，估计是你们学校代理的毛病
![image](https://user-images.githubusercontent.com/72654480/134182476-ed38898a-b122-48fa-9b50-f7f4927fb2ce.png)

**Comment by pigolaj121** [comment]
谢谢两位帮助了，今天才有空来看看，第一次见这种情况， 数据两头没问题，中间有问题，而且刚好只有1页的数据有问题，好几本都这样，凑活用吧
