### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 211wzy** [301Moved/ScienceDecrypting#17]
Traceback (most recent call last):
  File "gui.py", line 35, in decrypt_background
  File "decrypt.py", line 97, in decrypt_file
  File "xml\etree\ElementTree.py", line 1315, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B91099023EB7140DF8FAC836CE2BF2449000

**Comment by 301Moved** [comment]
科学文库上面下载大于1G的文件会被截断，导致文件格式错误。本来准备尝试手动修复一下文件格式强行解密，结果失败了，暂时没想到啥更好的办法。

**Comment by Xiang-SanJun** [comment]
这种有问题的可以找我帮你解决，请联系我，互帮互助。I use another 方法download.

**Comment by XY-QINGYI** [comment]
> 科学文库上面下载大于1G的文件会被截断，导致文件格式错误。本来准备尝试手动修复一下文件格式强行解密，结果失败了，暂时没想到啥更好的办法。

大佬求加一下好友？？？QQ：1518254900，微信18606832563

**Comment by 211wzy** [comment]
一般不会有问题了 遇到有问题的话我直接写邮件给出版社 ***@***.***
让他修改 如果解密的用不了的话 cajviewer也一定打不开，谢谢你！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月07日 22:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [301Moved/ScienceDecrypting] problem (#17) |

这种有问题的可以找我帮你解决，请联系我，互帮互助。I use another 方法download.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 301Moved** [comment]
鉴于你已经找到解决方案了，我先关闭这个issue，如果需要的话随时再开。

**Comment by 211wzy** [comment]
谢谢你的帮助！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月16日 02:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [301Moved/ScienceDecrypting] problem (#17) |

鉴于你已经找到解决方案了，我先关闭这个issue，如果需要的话随时再开。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
