### ISSUE TITLE
能否提供一下如何从科学文库上面下载图书吗？学校没有买这个数据库

### ISSUE THREAD

**Issue by hcb8174875** [301Moved/ScienceDecrypting#19]
最近刚发现这个网站，发现上面书籍很全但是学校没有购买。昨天在吾爱破解论坛上面看到一个使用调试工具进而打印全文的操作。但是打印出来很糊，这个网站能通过其他办法把文档爬取下来吗？

**Comment by 301Moved** [comment]
国家图书馆读者云门户可以下载

**Comment by hcb8174875** [comment]
科学文库上面的书籍还是很全的，国家图书馆找了几本都没有
