### ISSUE TITLE
解密出错：decrypt.CustomException: unable to find xref

### ISSUE THREAD

**Issue by CoCoThink** [301Moved/ScienceDecrypting#21]
----------------------------------------------------------------
Traceback (most recent call last):
  File "gui.py", line 35, in decrypt_background
    decrypt_file(src, dst)
  File "decrypt.py", line 124, in decrypt_file
    raise CustomException("unable to find xref")
decrypt.CustomException: unable to find xref

在解密这本书时出现的错误：
https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BE6E572A9C1274F27A430067EA60C61F6000
文件大小：34.1M

Thanks for your help！

**Comment by CoCoThink** [comment]
似乎是源文件就少了xref信息，可不可以提供一个选项，只解密文件，然后调用adobe等软件去修复文件

**Comment by 301Moved** [comment]
> 似乎是源文件就少了xref信息，可不可以提供一个选项，只解密文件，然后调用adobe等软件去修复文件

这个文件有问题，好像被截断了，很多关键信息都没有了。CAJ Viewer 应该也打不开这个文件吧？

**Comment by CoCoThink** [comment]
对，cajviewer也打不开

**Comment by 301Moved** [comment]
> 对，cajviewer也打不开

那无解了，应该是科学文库的 bug 🌚

**Comment by nicaicaii** [comment]
https://nicaicai.lanzouv.com/i8lOIxx8xfc
