### ISSUE TITLE
解密失败， unable to find xref

### ISSUE THREAD

**Issue by wllan** [301Moved/ScienceDecrypting#22]
Traceback (most recent call last):
  File "gui.py", line 35, in decrypt_background
  File "decrypt.py", line 124, in decrypt_file
decrypt.CustomException: unable to find xref

**Comment by XY-QINGYI** [comment]
哪一本书？？？给链接

**Comment by wllan** [comment]
https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BE1A947819F304F8C9B5504ED9BC42DAE000




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "301Moved/ScienceDecrypting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月8日(星期六) 晚上6:02
***@***.***&gt;;
抄送:&nbsp;"logan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [301Moved/ScienceDecrypting] 解密失败， unable to find xref (Issue #22)





 
哪一本书？？？给链接
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XY-QINGYI** [comment]
下好了你邮箱是？？？

**Comment by wllan** [comment]
> 下好了你邮箱是？？？

lerman@qq.com, 谢谢大哥！

**Comment by XY-QINGYI** [comment]
> Traceback (most recent call last): File "gui.py", line 35, in decrypt_background File "decrypt.py", line 124, in decrypt_file decrypt.CustomException: unable to find xref

下载下来不似加密的，只有11M但是仍然是矢量书籍，这由于kexuewenku加密导致文件变大，事实上的加密是服务器瞬时加密。

**Comment by XY-QINGYI** [comment]
> > 下好了你邮箱是？？？
> 
> [lerman@qq.com](mailto:lerman@qq.com), 谢谢大哥！

邮件查收下

**Comment by XY-QINGYI** [comment]
> > 下好了你邮箱是？？？
> 
> [lerman@qq.com](mailto:lerman@qq.com), 谢谢大哥！

有没有楼上大佬联系方式

**Comment by XY-QINGYI** [comment]
> > 下好了你邮箱是？？？
> 
> [lerman@qq.com](mailto:lerman@qq.com), 谢谢大哥！

加一下好友？？？？

**Comment by wllan** [comment]
> 

我没有耶

**Comment by wllan** [comment]
> > > 下好了你邮箱是？？？
> > 
> > 
> > [lerman@qq.com](mailto:lerman@qq.com), 谢谢大哥！
> 
> 有没有楼上大佬联系方式

我没有耶

**Comment by XY-QINGYI** [comment]
> > > > 下好了你邮箱是？？？
> > > 
> > > 
> > > [lerman@qq.com](mailto:lerman@qq.com), 谢谢大哥！
> > 
> > 
> > 有没有楼上大佬联系方式
> 
> 我没有耶

我QQ 1518254900 微信18606832563

**Comment by XY-QINGYI** [comment]
> https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BE1A947819F304F8C9B5504ED9BC42DAE000
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "301Moved/ScienceDecrypting" ***@***.***&gt;; 发送时间:&nbsp;2022年1月8日(星期六) 晚上6:02 ***@***.***&gt;; 抄送:&nbsp;"logan ***@***.******@***.***&gt;; 主题:&nbsp;Re: [301Moved/ScienceDecrypting] 解密失败， unable to find xref (Issue #22) 哪一本书？？？给链接 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

加我》？？？快点啊，我要删除联系方式了

**Comment by 301Moved** [comment]
fixed in 1.2.
