### ISSUE TITLE
目录乱码，内容空白

### ISSUE THREAD

**Issue by MD200MA** [301Moved/ScienceDecrypting#24]
这本书解密成功后，发现目录是乱码，内容空白，不知道是什么原因。麻烦大佬看一下，感谢。
链接是：https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=B28CA91E51D1048998709D04010ED5909000

**Comment by 301Moved** [comment]
CAJ Viewer也打不开，科学文库的bug

**Comment by MD200M** [comment]
原来是这样，谢谢大佬。我又看了一下。发现在线能打开，但下载到本地解密就会出问题，如果跟客服反映，说这本书下载后用CAJ Viewer打不开，这样可以吗？有没有大佬遇到过类似的情况？

**Comment by MD200M** [comment]
> CAJ Viewer也打不开，科学文库的bug
原来是这样，谢谢大佬。我又看了一下。发现在线能打开，但下载到本地解密就会出问题，如果跟客服反映，说这本书下载后用CAJ Viewer打不开，这样可以吗？有没有大佬遇到过类似的情况？

**Comment by 301Moved** [comment]
参考 #17  可以直接给科学文库发邮件让让他们修复

**Comment by MD200M** [comment]
好的，感谢
