### ISSUE TITLE
软件是否升级兼容知网国家标准

### ISSUE THREAD

**Issue by rffaxs** [301Moved/ScienceDecrypting#3]
中国知网的国家标准数据库（https://kns.cnki.net/kns8?dbcode=CISD）下载的pdf文件也是此种加密方式，抓包发现，提交验证服务器获取密码是正常的，但是解码模块出错。能否考虑支持此pdf?谢谢。

**Comment by 301Moved** [comment]
fixed.

**Comment by rffaxs** [comment]
👍👍👍！
刚才测试了下，发一个Bug，不知道是不是只是我这边问题。
测试了4个CNKI的GB，其中3个（如GB_T 23286.3-2021）快速翻页到结尾，Acrobat会提示本页面上存在错误。Acrobat可能无法正确显示页面...”，但是浏览页面也没发现不能显示的地方，估计是不是PDF解码时的部分结构细节没处理好。科学文库没有发现相关问题。建议能完善下，谢谢。
