### ISSUE TITLE
不知道怎们运用Python程序下载科学文库的电子书

### ISSUE THREAD

**Issue by Matthias-Kang** [301Moved/ScienceDecrypting#8]

**Comment by 301Moved** [comment]
出于防止被滥用的考虑，这里不提供下载科学文库文档的脚本，请自行手动下载。如果你特别需要某本书，而自己又没有办法下载的话，可以把书名提出来我帮你下。

**Comment by Matthias-Kang** [comment]
感谢您的回信。我是一名在读的一名本科生，由于自己的学习需求才想着在科学文库找一些电子资源。
如果您有时间的话能不能麻烦找一下这本书：
https://book.sciencereading.cn/shop/book/Booksimple/onlineRead.do?id=BA2D439244E765B9DE053020B0A0A190E000&amp;readMark=0
另外不知道方不方便以后有需求时在寻求您的帮助。
真挚的感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "301Moved/ScienceDecrypting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [301Moved/ScienceDecrypting] 不知道怎们运用Python程序下载科学文库的电子书 (#8)





 
出于防止被滥用的考虑，这里不提供下载科学文库文档的脚本，请自行手动下载。如果你特别需要某本书，而自己又没有办法下载的话，可以把书名提出来我帮你下。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 301Moved** [comment]
http://transfer.sh/1QSm2OV/%E6%A6%82%E7%8E%87%E8%AE%BA%EF%BC%88%E7%AC%AC%E4%B8%89%E7%89%88%EF%BC%89.pdf

**Comment by Matthias-Kang** [comment]
感谢您的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "301Moved/ScienceDecrypting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [301Moved/ScienceDecrypting] 不知道怎们运用Python程序下载科学文库的电子书 (#8)





 
http://transfer.sh/1QSm2OV/%E6%A6%82%E7%8E%87%E8%AE%BA%EF%BC%88%E7%AC%AC%E4%B8%89%E7%89%88%EF%BC%89.pdf
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Eumeryx** [comment]
其实可以注册一个国家图书馆的账号，从国家图书馆访问科学文库，可以下载大部分书籍。

**Comment by Matthias-Kang** [comment]
我注册了中国国家图书馆，可是还是无法阅读全文啊
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "301Moved/ScienceDecrypting"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [301Moved/ScienceDecrypting] 不知道怎们运用Python程序下载科学文库的电子书 (#8)





 
其实可以注册一个国家图书馆的账号，从国家图书馆访问科学文库，可以下载大部分书籍。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 301Moved** [comment]
国图上只能看出版日期早于2018年的书

**Comment by Matthias-Kang** [comment]
可惜了
